const express=require("express");
const cookieParser=require("cookie-parser");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const {Pool}=require("pg");
const fs=require("fs");
const path=require("path");

const app=express();
app.use(express.json({limit:"2mb"}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname,"public")));

const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const SECRET=process.env.JWT_SECRET||"change-this-secret";

async function db(q,p=[]){return (await pool.query(q,p)).rows}
async function init(){
 const schema=fs.readFileSync(path.join(__dirname,"db/schema.sql"),"utf8");
 await pool.query(schema);
 const n=(await pool.query("select count(*) from users")).rows[0].count;
 if(Number(n)===0){
  const u=process.env.ADMIN_USERNAME||"admin";
  const pw=process.env.ADMIN_PASSWORD||"123456";
  await pool.query("insert into users(username,password_hash,full_name,role) values($1,$2,$3,'admin')",[u,await bcrypt.hash(pw,12),"Quản trị viên"]);
 }
 await pool.query("insert into catalog(code,name,unit,fixed) values('CV00','Đã chuyển bản vẽ cho Phòng BT&GPMB','công trình',true) on conflict(code) do update set name=excluded.name,unit=excluded.unit,fixed=true");
 const tasks=[["CV01","Đo hiện trạng","thửa"],["CV02","Lập phiếu đo đạc","phiếu"],["CV03","Kiểm tra hồ sơ","hồ sơ"],["CV04","Kiểm kê tài sản","hộ"],["CV05","Xác định ranh","thửa"],["CV06","Hoàn thiện hồ sơ","hồ sơ"]];
 for(const t of tasks) await pool.query("insert into catalog(code,name,unit) values($1,$2,$3) on conflict(code) do nothing",t);
}
function token(u){return jwt.sign({id:u.id,role:u.role,name:u.full_name},SECRET,{expiresIn:"7d"})}
function auth(req,res,next){try{req.user=jwt.verify(req.cookies.bcddbt,SECRET);next()}catch{return res.status(401).json({error:"Chưa đăng nhập"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Chỉ Admin"});next()}

app.post("/api/login",async(req,res)=>{const {username,password}=req.body;const r=await db("select * from users where username=$1 and active=true",[username]);if(!r[0]||!(await bcrypt.compare(password,r[0].password_hash)))return res.status(401).json({error:"Sai tài khoản hoặc mật khẩu"});res.cookie("bcddbt",token(r[0]),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:604800000});res.json({id:r[0].id,username:r[0].username,name:r[0].full_name,role:r[0].role})});
app.post("/api/logout",(req,res)=>{res.clearCookie("bcddbt");res.json({ok:true})});
app.get("/api/me",auth,async(req,res)=>res.json(req.user));
app.get("/api/bootstrap",auth,async(req,res)=>{const projectSql=req.user.role==="admin"?"select p.*,coalesce(json_agg(json_build_object('id',u.id,'username',u.username,'full_name',u.full_name) order by u.full_name) filter (where u.id is not null),'[]') members from projects p left join project_members pm on pm.project_id=p.id left join users u on u.id=pm.user_id group by p.id order by p.id desc":"select p.*,coalesce(json_agg(json_build_object('id',u.id,'username',u.username,'full_name',u.full_name) order by u.full_name) filter (where u.id is not null),'[]') members from projects p join project_members me on me.project_id=p.id and me.user_id=$1 left join project_members pm on pm.project_id=p.id left join users u on u.id=pm.user_id group by p.id order by p.id desc";const reportSql=req.user.role==="admin"?"select r.*,p.code project_code,p.name project_name,u.full_name person from reports r join projects p on p.id=r.project_id join users u on u.id=r.user_id order by r.report_date desc,r.report_time desc,r.id desc":"select r.*,p.code project_code,p.name project_name,u.full_name person from reports r join projects p on p.id=r.project_id join users u on u.id=r.user_id where exists(select 1 from project_members pm where pm.project_id=r.project_id and pm.user_id=$1) order by r.report_date desc,r.report_time desc,r.id desc";const [projects,users,catalog,reports]=await Promise.all([
db(projectSql,req.user.role==="admin"?[]:[req.user.id]),
db("select id,username,full_name,role,active from users order by id"),
db("select id,code,name,unit,fixed,active from catalog where active=true order by fixed desc,id"),
db(reportSql,req.user.role==="admin"?[]:[req.user.id])
]);res.json({projects,users,catalog,reports})});
app.post("/api/users",auth,admin,async(req,res)=>{const {username,password,full_name,role="member"}=req.body;if(!username||!password||!full_name)return res.status(400).json({error:"Thiếu thông tin"});const r=await db("insert into users(username,password_hash,full_name,role) values($1,$2,$3,$4) returning id,username,full_name,role,active",[username,await bcrypt.hash(password,12),full_name,role]);res.json(r[0])});
app.put("/api/users/:id/status",auth,admin,async(req,res)=>{const active=Boolean(req.body.active);if(Number(req.params.id)===Number(req.user.id)&&!active)return res.status(400).json({error:"Không thể khóa tài khoản Admin đang đăng nhập"});const r=await db("update users set active=$1 where id=$2 returning id,username,full_name,role,active",[active,req.params.id]);if(!r[0])return res.status(404).json({error:"Không tìm thấy người dùng"});if(!active)await db("delete from project_members where user_id=$1",[req.params.id]);await db("insert into audit_logs(actor_id,action,detail) values($1,'update_user_status',$2)",[req.user.id,JSON.stringify({user_id:Number(req.params.id),active})]);res.json(r[0])});
app.post("/api/projects",auth,admin,async(req,res)=>{const {code,name,location="",expected_qty=0,status="Đang thực hiện",member_ids=[]}=req.body;if(!code||!name)return res.status(400).json({error:"Thiếu mã hoặc tên công trình"});const client=await pool.connect();try{await client.query("begin");const r=(await client.query("insert into projects(code,name,location,expected_qty,status) values($1,$2,$3,$4,$5) returning *",[code,name,location,Number(expected_qty||0),status])).rows[0];const ids=[...new Set((Array.isArray(member_ids)?member_ids:[]).map(Number).filter(Number.isInteger))];if(ids.length)await client.query("insert into project_members(project_id,user_id) select $1,id from users where id=any($2::int[]) and active=true and role<>'admin' on conflict do nothing",[r.id,ids]);await client.query("insert into audit_logs(actor_id,action,detail) values($1,'add_project',$2)",[req.user.id,JSON.stringify({project:r.id,member_ids:ids})]);await client.query("commit");res.json(r)}catch(e){await client.query("rollback");res.status(400).json({error:e.message})}finally{client.release()}});
app.put("/api/projects/:id",auth,admin,async(req,res)=>{const p=(await db("select * from projects where id=$1",[req.params.id]))[0];if(!p)return res.status(404).json({error:"Không tìm thấy công trình"});const {code,name,location="",expected_qty=0,status="Đang thực hiện"}=req.body;if(!code||!name)return res.status(400).json({error:"Thiếu mã hoặc tên công trình"});const r=await db("update projects set code=$1,name=$2,location=$3,expected_qty=$4,status=$5 where id=$6 returning *",[code,name,location,Number(expected_qty||0),status,p.id]);await db("insert into audit_logs(actor_id,action,detail) values($1,'edit_project',$2)",[req.user.id,JSON.stringify({project:p.id,old:{code:p.code,name:p.name,location:p.location,expected_qty:p.expected_qty,status:p.status},new:r[0]})]);res.json(r[0])});
app.get("/api/projects/:id/members",auth,admin,async(req,res)=>{const rows=await db("select u.id,u.username,u.full_name,u.role,u.active from project_members pm join users u on u.id=pm.user_id where pm.project_id=$1 order by u.full_name",[req.params.id]);res.json(rows)});
app.put("/api/projects/:id/members",auth,admin,async(req,res)=>{const projectId=Number(req.params.id),ids=[...new Set((Array.isArray(req.body.member_ids)?req.body.member_ids:[]).map(Number).filter(Number.isInteger))];const p=(await db("select id from projects where id=$1",[projectId]))[0];if(!p)return res.status(404).json({error:"Không tìm thấy công trình"});const client=await pool.connect();try{await client.query("begin");const before=(await client.query("select user_id from project_members where project_id=$1 order by user_id",[projectId])).rows.map(x=>x.user_id);await client.query("delete from project_members where project_id=$1",[projectId]);if(ids.length)await client.query("insert into project_members(project_id,user_id) select $1,id from users where id=any($2::int[]) and active=true and role<>'admin' on conflict do nothing",[projectId,ids]);const after=(await client.query("select user_id from project_members where project_id=$1 order by user_id",[projectId])).rows.map(x=>x.user_id);await client.query("insert into audit_logs(actor_id,action,detail) values($1,'update_project_members',$2)",[req.user.id,JSON.stringify({project:projectId,before,after})]);await client.query("commit");res.json({ok:true,member_ids:after})}catch(e){await client.query("rollback");res.status(400).json({error:e.message})}finally{client.release()}});
app.post("/api/catalog",auth,admin,async(req,res)=>{const {code,name,unit}=req.body;if(name==="Đã chuyển bản vẽ cho Phòng BT&GPMB")return res.status(400).json({error:"Công việc cố định không được thay đổi"});const r=await db("insert into catalog(code,name,unit) values($1,$2,$3) returning *",[code,name,unit]);res.json(r[0])});
app.put("/api/catalog/:id",auth,admin,async(req,res)=>{const c=(await db("select * from catalog where id=$1",[req.params.id]))[0];if(!c||c.fixed)return res.status(400).json({error:"Công việc cố định không được thay đổi"});const r=await db("update catalog set name=$1,unit=$2 where id=$3 returning *",[req.body.name,req.body.unit,c.id]);res.json(r[0])});
app.post("/api/reports",auth,async(req,res)=>{const {project_id,person_id,items=[]}=req.body;const uid=person_id||req.user.id;if(req.user.role!=="admin"&&Number(uid)!==Number(req.user.id))return res.status(403).json({error:"Thành viên chỉ được gửi báo cáo của mình"});const memberOk=(await db("select exists(select 1 from project_members where project_id=$1 and user_id=$2) ok",[project_id,uid]))[0]?.ok;if(!memberOk&&req.user.role!=="admin")return res.status(403).json({error:"Người thực hiện chưa được phân công vào công trình"});if(req.user.role==="admin"&&person_id&&!memberOk)return res.status(400).json({error:"Người thực hiện chưa được phân công vào công trình"});const out=[];const client=await pool.connect();try{await client.query("begin");for(const x of items){const qty=Number(x.qty||0),completed=Number(x.completed||0);if(qty<=0||completed>qty)throw new Error("Khối lượng không hợp lệ");const c=(await client.query("select id,name,unit from catalog where id=$1 and active=true",[x.task_id])).rows[0];if(!c)throw new Error("Công việc không tồn tại");const r=(await client.query("insert into reports(project_id,user_id,task_id,task_name,qty,completed,unit,note,review,direction,status,change_type) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'locked','new') returning *",[project_id,uid,c.id,c.name,qty,completed,c.unit,x.note||"",x.review||"",x.direction||""])).rows[0];out.push(r)}await client.query("commit");res.json(out)}catch(e){await client.query("rollback");res.status(400).json({error:e.message})}finally{client.release()}});
app.post("/api/reports/:id/request-edit",auth,async(req,res)=>{const r=(await db("select * from reports where id=$1",[req.params.id]))[0];if(!r)return res.status(404).json({error:"Không tìm thấy báo cáo"});if(req.user.role!=="admin"&&Number(r.user_id)!==Number(req.user.id))return res.status(403).json({error:"Không có quyền"});if(r.status!=="locked")return res.status(400).json({error:"Báo cáo không ở trạng thái khóa"});const reason=String(req.body.reason||"").trim(),v=req.body.proposed_changes||{};const qty=Number(v.qty??r.qty),completed=Number(v.completed??r.completed);if(!reason)return res.status(400).json({error:"Vui lòng nhập lý do chỉnh sửa"});if(!Number.isFinite(qty)||qty<=0||!Number.isFinite(completed)||completed<0||completed>qty)return res.status(400).json({error:"Khối lượng chỉnh sửa không hợp lệ"});const changes={qty,completed,note:String(v.note??r.note??""),review:String(v.review??r.review??""),direction:String(v.direction??r.direction??"")};const client=await pool.connect();try{await client.query("begin");const q=(await client.query("insert into edit_requests(report_id,requester_id,reason,proposed_changes) values($1,$2,$3,$4::jsonb) returning *",[r.id,req.user.id,reason,JSON.stringify(changes)])).rows[0];await client.query("update reports set status='edit_requested',edit_requested_at=now(),updated_at=now() where id=$1",[r.id]);await client.query("commit");res.json(q)}catch(e){await client.query("rollback");res.status(400).json({error:e.message})}finally{client.release()}});
app.get("/api/edit-requests",auth,admin,async(req,res)=>res.json(await db("select er.*,r.project_id,r.report_date,r.report_time,r.task_name,r.qty,r.completed,r.unit,u.full_name requester,p.code project_code,p.name project_name from edit_requests er join reports r on r.id=er.report_id join users u on u.id=er.requester_id join projects p on p.id=r.project_id where er.status='pending' order by er.id desc")));
app.post("/api/edit-requests/:id/approve",auth,admin,async(req,res)=>{const q=(await db("select * from edit_requests where status='pending' and (id=$1 or report_id=$1) order by case when report_id=$1 then 0 else 1 end,id desc limit 1",[req.params.id]))[0];if(!q)return res.status(404).json({error:"Không tìm thấy yêu cầu duyệt đang chờ. Hãy tải lại trang."});const c=q.proposed_changes||{};const before=(await db("select * from reports where id=$1",[q.report_id]))[0];if(!before)return res.status(404).json({error:"Không tìm thấy báo cáo liên kết với yêu cầu"});const client=await pool.connect();try{await client.query("begin");const r=(await client.query("update reports set qty=$1,completed=$2,note=$3,review=$4,direction=$5,status='locked',change_type='changed',edit_approved_at=now(),updated_at=now() where id=$6 returning *",[Number(c.qty),Number(c.completed),c.note||"",c.review||"",c.direction||"",q.report_id])).rows[0];await client.query("update edit_requests set status='approved',reviewed_at=now(),reviewer_id=$1 where id=$2",[req.user.id,q.id]);await client.query("insert into audit_logs(actor_id,action,detail) values($1,'approve_edit_request',$2)",[req.user.id,JSON.stringify({request_id:q.id,report_id:q.report_id,reason:q.reason,project_id:r.project_id,task_name:r.task_name,old_values:{qty:before.qty,completed:before.completed,note:before.note,review:before.review,direction:before.direction},new_values:c,summary:"Admin đã duyệt và áp dụng nội dung chỉnh sửa"})]);await client.query("commit");res.json({ok:true,report:r,request_id:q.id})}catch(e){await client.query("rollback");res.status(400).json({error:e.message})}finally{client.release()}});
app.put("/api/reports/:id",auth,async(req,res)=>{const r=(await db("select * from reports where id=$1",[req.params.id]))[0];if(!r)return res.status(404).json({error:"Không tìm thấy"});if(req.user.role!=="admin"&&!(r.status==="editing"&&r.user_id===req.user.id))return res.status(403).json({error:"Chưa được phép sửa"});const qty=Number(req.body.qty),completed=Number(req.body.completed);if(qty<=0||completed>qty)return res.status(400).json({error:"Khối lượng không hợp lệ"});const x=await db("update reports set qty=$1,completed=$2,note=$3,review=$4,direction=$5,status='locked',change_type='changed',updated_at=now() where id=$6 returning *",[qty,completed,req.body.note||"",req.body.review||"",req.body.direction||"",r.id]);await db("insert into audit_logs(actor_id,action,detail) values($1,'edit_report',$2)",[req.user.id,JSON.stringify({report:r.id,old_qty:r.qty,new_qty:qty})]);res.json(x[0])});
app.get("/api/summary",auth,async(req,res)=>{const projects=await db("select p.*,coalesce(sum(case when c.fixed=true then r.completed else 0 end),0) completed from projects p left join reports r on r.project_id=p.id left join catalog c on c.id=r.task_id group by p.id order by p.id");res.json(projects)});
app.get("/api/audit",auth,admin,async(req,res)=>res.json(await db("select a.*,u.full_name from audit_logs a left join users u on u.id=a.actor_id order by a.id desc limit 500")));
app.get("/{*splat}",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));

init().then(()=>app.listen(process.env.PORT||3000,()=>console.log("BaoCaoCongViec V2.0 running"))).catch(e=>{console.error(e);process.exit(1)});
